language: node_js
node_js:
  - "8"
before_script:
  - npm install -g gulp-cli
script: gulp pack
deploy:
  provider: releases
  api_key:
    secure: dzcQqJpvF2ZIVZyKdnhG3hGzTTTx+ELVik0D4FXXCfT/VbZ4/NZTFWU5YFvqFMQ7oa1NI5zm37wGtp7byYCgunkJnVB6lHvU3aYQqCSkE2OGWHyN8r4umicjkln1+Pqlde5XeUibZRN9pcTFssR4ErYRvH0c7zEtn/DWZSbQL33ASQjxxTVHnHK7olIVJFuY0I0rYcFBPwe8ZiPxYXjcQdD9zOROF2zj6tuaFnIWI7tCa00bZ/lqbwJ1vg2xngVTUlSnAziHdIC6YfQXJ5WnU2fru2gDUTAKAsaChAumUHL9CSFltcu15K6h8XxVgxZBxhnmelaalfdlDMoDbhBftCDFJ71akQly/EeQaKjyofwcfgBgybbRO6wkwXX0MUj+51EVBlki+HNdVXgq1bGGA7fDMWsGsPnQJGhgjs0ZAT2b7TUUBF329PT9w6jd0jOZUM66hCCs1YX5Bar8hjU8DGkRukE9ARC/+wkTir4nVPQWMUs0QEvhPGrJrMKtV4KZMelyD216nJfqQrL9XORgt9BnL/m9JQWtYhnbFdxYkBA7nEl413EW+9gS0OsWcb8pl1ZJ8jqUqExiEqGaqKS0RyHImg4q7yPDyUtnju1Xm9CEdbtGtf7+56z7munohfbGABinHYI7bkRIEXG4B6POXIAGGZ9C3MTP19QvPw+5GI4=
  file:
    - build/ui-bundle.zip
  skip_cleanup: true
  on:
    repo: gmarpons/ethical-digital-standards-ui
    tags: true
