'use strict'

const jsdom = require("jsdom")
const { JSDOM } = jsdom

module.exports = (html) => {
  const dom = new JSDOM(html.toString('utf-8'))
  const { document } = dom.window

  // Replace the TOC generated by Asciidoctor by something similar to
  // https://github.com/Kozea/WeasyPrint/pull/652#issuecomment-403276559.
  for (let li of document.querySelectorAll('#toc li')) {
    let a = li.querySelector('a')
    a.textContent = ''
    let a1 = a.cloneNode()
    let a2 = a.cloneNode()
    a1.classList.add('toctext')
    a2.classList.add('tocpagenr')
    let pair = document.createElement('div')
    pair.appendChild(a1)
    pair.appendChild(a2)
    li.replaceChild(pair, a)
  }

  // Change tag of #toctitle from <div> to <h3>, to make it appear in the PDF outline.
  let toc = document.getElementById('toc')
  if (toc) {
    let tocTitleOld = toc.querySelector('#toctitle')
    let tocTitleNew = document.createElement('h3')
    tocTitleNew.className = tocTitleOld.className
    tocTitleNew.textContent = tocTitleOld.textContent
    toc.replaceChild(tocTitleNew, tocTitleOld)
  }

  // Add custom attribute "data-measure-id" to measure titles
  for (let m of document.querySelectorAll('.measure, .recommendation, .alternative')) {
    let title = m.querySelector('.content').querySelector('.title')
    title.setAttribute('data-measure-id', m.getAttribute('id'))
  }

  let result = ''
  for (let node of document.documentElement.childNodes)
    result = result + node.innerHTML

  return result
}

// Example of selector for TOC: 'h2:not(.no-toc), h3:not(.no-toc)'
